### ISSUE TITLE
First person left hand renders as a copy of the right hand, with inappropriate positioning

### ISSUE THREAD

**Issue by floral-qua-floral** [Gamepiaynmo/CustomPlayerModel#11]
The left hand in first person mode appears as a duplicate of the right hand, and is positioned incorrectly, making it completely or almost completely out of frame most of the time. This is an issue specific to the left hand, _not_ the offhand - if the main hand is set to Left in Skin Customizations, the offhand will render just fine, as the right hand has no issues.

I've slightly modified the Zombified Piglin example model (which seems to have been removed from the Github?) to more easily demonstrate this issue. I modified the model to have a bright blue right hand and a bright red left hand. I also modified the `model.json` file to specify right_arm_c as the first-person right hand bone, and left_hand_c as the left hand - however this didn't seem to change anything, the issue is the same regardless of whether this is present in the file; in fact, it appears that the "left_arm" field might be being ignored entirely. The model can be downloaded here: [zombified_piglin.zip](https://github.com/Gamepiaynmo/CustomPlayerModel/files/7048758/zombified_piglin.zip)

In this screenshot, I confirm that the different-coloured hands are rendering correctly on the third person model. I have also placed a map into my offhand and set my Main Hand setting in Skin Customization to "Right": ![image](https://user-images.githubusercontent.com/49110090/130837395-447c1c61-d270-47a7-98b2-abb7e7fa7a78.png)

Once I switch to first person, the left hand which is holding the map appears are the incorrect position (indicated with a pink arrow, as it is a bit hard to spot behind the hotbar), and has a blue tip instead of the red one that the actual left hand should have: ![image](https://user-images.githubusercontent.com/49110090/130837648-f7486ebd-210c-4bcb-b44a-71e1f81e848b.png)

By switching to the vanilla model instead of a CPM model, the correct positioning can be observed: ![image](https://user-images.githubusercontent.com/49110090/130837858-92f1a8a0-1241-402f-9717-09945bf544c7.png)

The left hand is entirely out of frame when holding a map in the mainhand with an empty offhand. None of these issues apply to the right hand when Main Hand is switched to "Left", however they do continue to affect the left hand. Additionally, when the left hand is set to be the main hand and an empty hotbar slot is selected, the left hand will appear hidden behind the hotbar: ![image](https://user-images.githubusercontent.com/49110090/130839289-e757f04a-b036-433b-b8f8-e786ba100486.png)

**Comment by Gamepiaynmo** [comment]
Fixed in 2.2.4.
