### ISSUE TITLE
Unable to use models on vanilla servers

### ISSUE THREAD

**Issue by Cart555** [Gamepiaynmo/CustomPlayerModel#12]
I am unable to select a model when on a server without the mod, the GUI still pops up and I’m able to load the model on single player, any help is appreciated.

**Comment by val9k** [comment]
is your model name appear yellow in the GUI? this mean your model is store in a normal file and is in edit mode. you need to place the model in a zip file (same folder) and it should solve the issue.

**Comment by Cart555** [comment]
I’ll try this when I can, thank you!

**Comment by Cart555** [comment]
> is your model name appear yellow in the GUI? this mean your model is store in a normal file and is in edit mode. you need to place the model in a zip file (same folder) and it should solve the issue.

That worked! I do have another issue though, I tried to get it to work on a modded server that doesn’t have the mod and it told me I had a mismatched modlist, any way to fix this?

**Comment by val9k** [comment]
>  I do have another issue though, I tried to get it to work on a modded server that doesn’t have the mod and it told me I had a mismatched modlist, any way to fix this?
Sorry, i don't know because this issue is more of a forge probleme than CPM (i think). maybe you can ask on the [CPM discord](https://discord.gg/uVT39n5) if other people know.

**Comment by art0007i** [comment]
I think this should be closed since the original issue has already been resolved, on GitHub it's generally advised to make a new issue for each new problem instead of commenting a new problem under an unrelated issue
