### ISSUE TITLE
[request] make the mode client side

### ISSUE THREAD

**Issue by val9k** [Gamepiaynmo/CustomPlayerModel#13]
right now, the mod request to be on client and server (the 1.16.5 forge version at least). which mean if you try to connect to a modded server that don't have CPM, you get an error message.
is it possible to make the mod client side so that you can go to a server that have other mod but not CPM and still be able to connect.

(this is a follow up of issue #12 )

**Comment by art0007i** [comment]
[Here](https://mcforge.readthedocs.io/en/1.16.x/concepts/sides/#writing-one-sided-mods) is a page from the forge docs that should help with this issue

**Comment by Gamepiaynmo** [comment]
Fixed in 2.2.4.
