### ISSUE TITLE
unable to open the GUI in a vanilla server if it was previously open in a single player world

### ISSUE THREAD

**Issue by val9k** [Gamepiaynmo/CustomPlayerModel#14]
If you go to a single player world, open the CPM GUI, then go to a vanilla server, you wont be able to open the GUI. However, if after starting the game you go straight to the same vanilla server, you can open the GUI and select a model.

this is an old bug but i think it wasn't reported here so now it is.

**Comment by Gamepiaynmo** [comment]
Fixed in 2.2.5.
