### ISSUE TITLE
server crash during map loading with CPM

### ISSUE THREAD

**Issue by val9k** [Gamepiaynmo/CustomPlayerModel#15]
i tried to start a minecraft forge server with CPM (to do some test) and i can't start and connect to the server.
the server only have CPM (version 2.2.4) (and i try with and without obfuscated) and i try with a world or starting the server without a world. in any configuration, the server is not usable:
-if there is no world, it will crash during the world generation;
-if there is a world to load, it will fail to load it but not crash, but connecting to the server will result in a internal server error.

client side, i have forge 36.1.6, CPM 2.2.4, obfuscated 0.6.2, jei, invtweaks and Optifine, all of wich are client side and regardless, the errore happen in the console befor the server is available so i don't think it is the issue.

I don't have the crash repport but i have two log, one with only CPM and no world, one with CPM and obfuscated and a world created by a forge server with no mod.

[just CPM & no world.log](https://github.com/Gamepiaynmo/CustomPlayerModel/files/7153290/just.CPM.no.world.log)
[CPM, obfuscated & world.log](https://github.com/Gamepiaynmo/CustomPlayerModel/files/7153291/CPM.obfuscated.world.log)

**Comment by val9k** [comment]
nb, there is multiple crash repport in the just CPM & no world.log, the first is line 4959 and the last one is line 37138

**Comment by Gamepiaynmo** [comment]
Fixed in 2.2.5.
