### ISSUE TITLE
can't ask for password reset on cpmmod.top

### ISSUE THREAD

**Issue by ghost** [Gamepiaynmo/CustomPlayerModel#16]
it is not directly an issue about the mod but the website cpmmod.top

when you click on [Forgot Your Password?](http://cpmmod.top/password/reset) and you enter a adresse link to an acount, you get an error.

the issue doesn't appear if the email you enter is not link to an actual acount.

btw yes i forgot my cpmmod.top password:)
![image](https://user-images.githubusercontent.com/52279972/133777635-2c766211-0600-4f62-93c3-0570dc3500e4.png)

**Comment by Gamepiaynmo** [comment]
Fixed. Should be able to receive emails now.
