### ISSUE TITLE
NullPointerException when trying to render attachment with empty list

### ISSUE THREAD

**Issue by SupersonicNK** [Gamepiaynmo/CustomPlayerModel#2]
## Version Info
Minecraft: 1.16.5
Forge: 36.0.43
CPM: 2.1.0

## Report Info
Upon rendering an attachment that has been given an empty list, the game crashes with the following reason: `java.lang.NullPointerException: Rendering entity in world`
This has been tested with the following attachments so far, resulting in the same reason (but a different stacktrace):
- helmet (crash report given)
- chestplate_body
- chestplate_left
- chestplate_right
- leggings_body
- leggings_left
- leggings_right
- boots_left
- boots_right
- item_right (crash report given)
- elytra (crash report given)
- parrot_left (crash report given)

Hiding armor does work via the client config.

## Steps to reproduce
1. Create a new model or use a pre-existing model. Disable an attachment by providing it an empty list. 
2. Hold an item or equip an armor in the slot that would normally render using that attachment.
3. Allow the game to render it (via third-person, inventory, or cpm model selection screen.)

## Crash Reports
item_right: https://pastebin.com/ebdFXG0d
helmet: https://pastebin.com/nW9kd3HK
(all armor crashes point to the same line at the top of the stacktrace.)
elytra: https://pastebin.com/ZC8s8Xeb
parrot_left: https://pastebin.com/iE0MykJe

**Comment by Gamepiaynmo** [comment]
Fixed in version 2.1.1 beta.
