### ISSUE TITLE
no "open skin editor" option in the main menu on TL

### ISSUE THREAD

**Issue by RyungoesBRRU** [Gamepiaynmo/CustomPlayerModel#26]
there is no open skin editior option in the games main menu or in the skin customization option in TLauncher 
i wanted to use this mod for the ++animation project and have custom models to make the game feel less rigid
if this isnt an issue, is there any other way i can add ++animation project in CPM?

**Comment by ghost** [comment]
Hello.
This is the wrong CPM mod.
This is custom player models, you want to use [Customizable player model](https://www.curseforge.com/minecraft/mc-mods/custom-player-models). These are two different mod. They do similar things but this one doesn't have an ingame skin editor and use javascript files for the animation.

Have a nice day.

**Comment by RyungoesBRRU** [comment]
>my pain is immeasurable and my day is ruined

**Comment by RyungoesBRRU** [comment]
but thanks for letting me know though
