### ISSUE TITLE
Mysterious CTD when opening the mod UI

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [Gamepiaynmo/CustomPlayerModel#3]
Not much to say, trying to open the mod's selection menu crashes the game outright, and dunno what might be causing the conflict, and if it can be fixed on your side.
[crash-2021-03-29_22.52.46-client.txt](https://github.com/Gamepiaynmo/CustomPlayerModel/files/6224482/crash-2021-03-29_22.52.46-client.txt)

**Comment by DcNdrew** [comment]
Confirmed.

**Comment by dragon-evol** [comment]
Same error +1, but I'm using a model I used in 1.12.2, not sure if that's the problem. Also don't know if it has something to do with other mods in my modpack.
