### ISSUE TITLE
Aiming is borken with MrCrayfish's Gun Mod

### ISSUE THREAD

**Issue by juraj-hrivnak** [Gamepiaynmo/CustomPlayerModel#4]
- 1.16

![2021-07-04_13 04 40](https://user-images.githubusercontent.com/71150936/124382838-b188c580-dcc9-11eb-875f-ab7d7a6762c5.png)
![2021-07-04_13 04 53](https://user-images.githubusercontent.com/71150936/124382843-b3528900-dcc9-11eb-952b-afd68db87511.png)

**Comment by Gamepiaynmo** [comment]
Fixed in 2.2.2.
