### ISSUE TITLE
entity.getLimbSwing() and entity.getAnimPosition() are switch with entity.getAnimSpeed()

### ISSUE THREAD

**Issue by val9k** [Gamepiaynmo/CustomPlayerModel#5]
In the 2.2.0 version of the mod, if in the tick function of the anim file you call entity.getLimbSwing() or entity.getAnimPosition(), you get the speed of the animation and if you call entity.getAnimSpeed(), you get the position in the animation.

**Comment by Gamepiaynmo** [comment]
Fixed in 2.1.1.
